FROM debian

LABEL maintainer="git@ashleypoole.co.uk"
LABEL description="This is a Debian based Linux image containing Cloudflare Argo Tunnel"

RUN apt-get update && apt-get install -y netcat

WORKDIR /cloudflare

COPY cert.pem /root/.cloudflare-warp/cert.pem
COPY startup-tunnel.sh ./

ADD https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-amd64.tgz .
RUN tar xzf *.tgz

ENTRYPOINT ["/cloudflare/cloudflared", "tunnel"]