version: '3'
services:

  response:
    build:
      context: .
      dockerfile: Dockerfile.response
    image: response
    container_name: response
    entrypoint: bash
    command: /app/startup.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES: "true"
    env_file: .env
    volumes:
      - ./:/app
    stdin_open: true
    tty: true

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    image: cron
    container_name: cron
    depends_on:
      - response
    tty: true

  db:
    image: "postgres:11.2"
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  tunnel:
    build:
      context: .
      dockerfile: Dockerfile.tunnel
    image: argotunnel
    container_name: tunnel
    environment:
      - TUNNEL_URL=http://response:8000
      - TUNNEL_HOSTNAME=${TUNNEL_HOSTNAME}
    depends_on:
      - cron
      - response

volumes:
  postgres_data:
