version: '3'
services:

  response:
    build:
      context: ../
      dockerfile: Dockerfile.response.sql
    image: response
    container_name: response
    entrypoint: bash
    command: /app/startup.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES: "false"
      SQL_SERVER: "true"
      TUNNEL_HOSTNAME: "${TUNNEL_HOSTNAME}"
    env_file: ../.env
    volumes:
      - ../:/app
    stdin_open: true
    tty: true

  cron:
    build:
      context: ../
      dockerfile: Dockerfile.cron
    image: cron
    container_name: cron
    depends_on:
      - response
    tty: true

  db:
    image: "mcmoe/mssqldocker:latest"
    container_name: response-sqlserver
    environment: 
      SA_PASSWORD: "admin123!"
      ACCEPT_EULA: "Y"
      MSSQL_DB: "ResponseDB"
      MSSQL_USER: "response"
      MSSQL_PASSWORD: "response123!"
    ports:
      - "3433:1433"

  tunnel:
    build:
      context: ../
      dockerfile: Dockerfile.tunnel
    image: argotunnel
    container_name: tunnel
    entrypoint: bash
    command: /cloudflare/startup-tunnel.sh
    environment:
      - TUNNEL_URL=http://response:8000
      - TUNNEL_HOSTNAME=${TUNNEL_HOSTNAME}
    depends_on:
      - cron
      - response